from django.shortcuts import render

def landing(request): return render(request, "pages/landing.html")
def test_page(request): return render(request, "pages/test.html")
def login_page(request): return render(request, "pages/login.html")
def register_page(request): return render(request, "pages/register.html")
def pricing(request): return render(request, "pages/pricing.html")
def dashboard(request): return render(request, "pages/dashboard.html")
def history(request): return render(request, "pages/history.html")
def applications(request): return render(request, "pages/applications.html")
def application_detail(request, app_id): return render(request, "pages/application_detail.html", {"app_id": app_id})
def usage(request): return render(request, "pages/usage.html")
def docs(request): return render(request, "pages/docs.html")
def account(request): return render(request, "pages/account.html")
def asr_ui(request): return render(request, "pages/asr_recorder.html")
